server:
  port: 9091

# MySql Datasource Properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/breath_easy_identity
    username: root
    password: Raza
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
  expirationTime: 30000000
  refreshTokenExpirationTime: 90000000
